### ISSUE TITLE
Can't convert np ndarray of type numpy.object

### ISSUE THREAD

**Issue by anirban1513** [med-air/Contrastive-COVIDNet#1] opened 2021-01-24 05:53 UTC
![image](https://user-images.githubusercontent.com/45719623/105622316-c4ee5580-5e3a-11eb-8267-1dc461c89ff8.png)

**Comment by Kyfafyd** [comment] 2021-01-24 07:27
Hi, dear Anirban, thanks very much for your interest in our work.

I have checked the error. I found it may be caused by different versions of `numpy`.
For your easy use, I export my conda environment in `environment.yaml`, you can refer to `readme` update.

If you have further questions, please feel free to contact me.

**Comment by anirban1513** [comment] 2021-01-24 07:45
Thank you So much. It works now. I can train it.

**Comment by anirban1513** [comment] 2021-01-24 08:56
I could run the exact same code. The testing accuracy is much lower than your given model. I don't know the reason. The code is using the best_checkpoint file trained in my pc. (The model that you gave us showed higher testing accuracy))

I am giving you the testing result
![image](https://user-images.githubusercontent.com/45719623/105625560-4e5e5180-5e54-11eb-91c0-be2c9d39a3ef.png)
![image](https://user-images.githubusercontent.com/45719623/105625582-78177880-5e54-11eb-807e-2651ea55f75e.png)

**Comment by Kyfafyd** [comment] 2021-01-24 13:04
I am so sorry that I have forgotten to change back following two lines after running comparsion methods.
https://github.com/med-air/Contrastive-COVIDNet/blob/adc5cbb199149f289a78c171ee7656ba444a4e82/code/train.py#L85
https://github.com/med-air/Contrastive-COVIDNet/blob/adc5cbb199149f289a78c171ee7656ba444a4e82/code/train.py#L174
It is fixed now. Besides, I have modified `test.py` a bit for much more elegant output.

**Closed as completed** 2021-04-03 15:12 UTC
